// Regenerate src/wire.d.ts from the drift-tested schema the Python side exports.
import { compile } from "json-schema-to-typescript";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "../../protocol/v1/neurogarden.schema.json");
const outPath = resolve(here, "../src/wire.d.ts");

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
const banner =
  "/* Generated by `npm run types` from protocol/v1/neurogarden.schema.json — do not edit. */\n";
const types = await compile(schema, "NeuroGardenProtocol", {
  bannerComment: banner,
  additionalProperties: false,
  style: { singleQuote: false, semi: true, printWidth: 100 },
});
writeFileSync(outPath, types);
console.log(`wrote ${outPath}`);
