/* Generated by `npm run types` from protocol/v1/neurogarden.schema.json — do not edit. */

/**
 * Envelope {v, type, payload}; unknown types are ignored by receivers.
 */
export type NeuroGardenProtocolV1 = ClientMessage | ServerMessage;
export type ClientMessage =
  HelloMessage | JoinMessage | ActionMessage | LeaveMessage | SayMessage | ReplayMessage;
export type Client = string;
export type Owner = string;
export type Protocol = number;
export type Role = "agent" | "spectator";
export type Token = string;
export type Type = "hello";
export type V = 1;
export type Body = "fly";
export type Type1 = "join";
export type V1 = 1;
export type Action1 = number;
export type Tick = number;
export type Type2 = "action";
export type V2 = 1;
export type Type3 = "leave";
export type V3 = 1;
export type Text = string;
export type Type4 = "say";
export type V4 = 1;
export type Lineage = number;
export type Owner1 = string;
export type Speed = number;
export type Type5 = "replay";
export type V5 = 1;
export type ServerMessage =
  | WelcomeMessage
  | JoinedMessage
  | ObservationMessage
  | DiedMessage
  | WorldMessage
  | FrameMessage
  | ChronicleMessage
  | ErrorMessage
  | ReplayInfoMessage;
export type Actions = string[];
export type Centre = number[] | null;
export type Dtype = string;
export type High = number;
export type Low = number;
export type NorthUp = boolean | null;
export type Shape = number[];
export type Frame = string;
export type Motd = string;
export type Owner2 = string;
export type Protocol1 = number;
export type Role1 = "agent" | "spectator";
export type DawnEnd = number;
export type DayLength = number;
export type DuskStart = number;
export type Height = number;
export type Name = string;
export type NightStart = number;
export type RulesVersion = number;
export type Tps = number;
export type Width = number;
export type Type6 = "welcome";
export type V6 = 1;
export type AgentId = number;
export type Lineage1 = number;
export type Name1 = string;
export type Reattached = boolean;
export type Tick1 = number;
export type Type7 = "joined";
export type V7 = 1;
export type Body1 = number[];
export type Env = number[];
export type Smell = number[][];
export type Touch = number[];
export type Vision = number[][][];
export type DeadlineMs = number;
export type Type8 = string;
export type Events1 = AgentEvent[];
export type Missed = number;
export type Tick2 = number;
export type Type9 = "observation";
export type V8 = 1;
export type AgentId1 = number;
export type Causes = string[];
export type Lineage2 = number;
export type Name2 = string;
export type Bites = number;
export type Bumps = number;
export type Days = number;
export type DeathCauses = string[];
export type Drinks = number;
export type Lifespan = number;
export type MeanWellbeing = number;
export type RestTicks = number;
export type TilesExplored = number;
export type Tick3 = number;
export type Type10 = "died";
export type V9 = 1;
export type Height1 = number;
export type MapName = string;
export type Terrain = number[][];
export type Width1 = number;
export type Type11 = "world";
export type V10 = 1;
export type Age = number;
export type AgentId2 = number;
export type Alive = boolean;
export type Connected = boolean;
export type Energy = number;
export type Facing = number;
export type Health = number;
export type Hydration = number;
export type Lineage3 = number;
export type Mood = string;
export type Name3 = string;
export type Owner3 = string;
export type Satiety = number;
export type Say1 = string;
export type X = number;
export type Y = number;
export type Agents = AgentView[];
export type Day = number;
export type AgentId3 = number | null;
export type Type12 = string;
export type Events2 = WorldEvent[];
export type Light = number;
export type Amount = number;
export type Kind = number;
export type X1 = number;
export type Y1 = number;
export type Resources = ResourceView[];
export type Alive1 = boolean;
export type BestLifespan = number;
export type BestLineage = number;
export type Lives = number;
export type Owner4 = string;
export type Scores = OwnerScore[];
export type Tick4 = number;
export type Type13 = "frame";
export type V11 = 1;
export type Text1 = string;
export type Tick5 = number;
export type Type14 = "chronicle";
export type V12 = 1;
export type Code = string;
export type Fatal = boolean;
export type Message = string;
export type Type15 = "error";
export type V13 = 1;
export type BornTick = number;
export type Causes1 = string[];
export type DiedTick = number | null;
export type Done = boolean;
export type Lifespan1 = number | null;
export type Lineage4 = number;
export type Name4 = string;
export type Owner5 = string;
export type Speed1 = number;
export type Type16 = "replay";
export type V14 = 1;

export interface HelloMessage {
  payload: Hello;
  type?: Type;
  v?: V;
}
export interface Hello {
  client?: Client;
  owner: Owner;
  protocol: Protocol;
  role: Role;
  token: Token;
}
export interface JoinMessage {
  payload?: Join;
  type?: Type1;
  v?: V1;
}
export interface Join {
  body?: Body;
}
export interface ActionMessage {
  payload: Action;
  type?: Type2;
  v?: V2;
}
export interface Action {
  action: Action1;
  tick: Tick;
}
export interface LeaveMessage {
  payload?: Leave;
  type?: Type3;
  v?: V3;
}
export interface Leave {}
export interface SayMessage {
  payload: Say;
  type?: Type4;
  v?: V4;
}
/**
 * A brain's thought bubble: plain text spectators can see over the fly.
 */
export interface Say {
  text: Text;
}
export interface ReplayMessage {
  payload: Replay;
  type?: Type5;
  v?: V5;
}
/**
 * A spectator asks to watch an archived life again: a ghost, at `speed` × the world's pace.
 */
export interface Replay {
  lineage: Lineage;
  owner: Owner1;
  speed?: Speed;
}
export interface WelcomeMessage {
  payload: Welcome;
  type?: Type6;
  v?: V6;
}
export interface Welcome {
  catalog: Catalog;
  motd?: Motd;
  owner: Owner2;
  protocol: Protocol1;
  role: Role1;
  world: WorldInfo;
}
export interface Catalog {
  bodies: Bodies;
  constants: Constants;
  events?: Events;
}
export interface Bodies {
  [k: string]: BodyInfo;
}
export interface BodyInfo {
  actions: Actions;
  channels: Channels;
  frame: Frame;
}
export interface Channels {
  [k: string]: ChannelInfo;
}
export interface ChannelInfo {
  axes?: Axes;
  centre?: Centre;
  dtype: Dtype;
  high: High;
  low: Low;
  north_up?: NorthUp;
  shape: Shape;
  tables?: Tables;
}
export interface Axes {
  [k: string]: string[];
}
export interface Tables {
  [k: string]: {
    [k: string]: number;
  };
}
export interface Constants {
  [k: string]: number;
}
export interface Events {
  [k: string]: string[];
}
export interface WorldInfo {
  dawn_end: DawnEnd;
  day_length: DayLength;
  dusk_start: DuskStart;
  height: Height;
  name: Name;
  night_start: NightStart;
  rules_version: RulesVersion;
  tps: Tps;
  width: Width;
}
export interface JoinedMessage {
  payload: Joined;
  type?: Type7;
  v?: V7;
}
export interface Joined {
  agent_id: AgentId;
  lineage: Lineage1;
  name: Name1;
  reattached: Reattached;
  tick: Tick1;
}
export interface ObservationMessage {
  payload: Observation;
  type?: Type9;
  v?: V8;
}
export interface Observation {
  channels: Channels1;
  deadline_ms: DeadlineMs;
  events: Events1;
  missed: Missed;
  tick: Tick2;
}
export interface Channels1 {
  body: Body1;
  env: Env;
  smell: Smell;
  touch: Touch;
  vision: Vision;
}
export interface AgentEvent {
  data?: Data;
  type: Type8;
}
export interface Data {
  [k: string]: unknown;
}
export interface DiedMessage {
  payload: Died;
  type?: Type10;
  v?: V9;
}
export interface Died {
  agent_id: AgentId1;
  causes: Causes;
  lineage: Lineage2;
  name: Name2;
  stats: Stats;
  tick: Tick3;
}
export interface Stats {
  bites: Bites;
  bumps: Bumps;
  days: Days;
  death_causes: DeathCauses;
  drinks: Drinks;
  lifespan: Lifespan;
  mean_wellbeing: MeanWellbeing;
  rest_ticks: RestTicks;
  tiles_explored: TilesExplored;
}
export interface WorldMessage {
  payload: WorldMap;
  type?: Type11;
  v?: V10;
}
export interface WorldMap {
  height: Height1;
  map_name: MapName;
  terrain: Terrain;
  width: Width1;
}
export interface FrameMessage {
  payload: Frame1;
  type?: Type13;
  v?: V11;
}
export interface Frame1 {
  agents: Agents;
  day: Day;
  events: Events2;
  light: Light;
  resources: Resources;
  scores: Scores;
  tick: Tick4;
}
export interface AgentView {
  age: Age;
  agent_id: AgentId2;
  alive: Alive;
  connected: Connected;
  energy: Energy;
  facing: Facing;
  health: Health;
  hydration: Hydration;
  lineage: Lineage3;
  mood: Mood;
  name: Name3;
  owner: Owner3;
  satiety: Satiety;
  say?: Say1;
  x: X;
  y: Y;
}
export interface WorldEvent {
  agent_id: AgentId3;
  data?: Data1;
  type: Type12;
}
export interface Data1 {
  [k: string]: unknown;
}
/**
 * One thing worth eating or drinking, where a spectator can see it.
 */
export interface ResourceView {
  amount: Amount;
  kind: Kind;
  x: X1;
  y: Y1;
}
export interface OwnerScore {
  alive: Alive1;
  best_lifespan: BestLifespan;
  best_lineage?: BestLineage;
  lives: Lives;
  owner: Owner4;
}
export interface ChronicleMessage {
  payload: Chronicle;
  type?: Type14;
  v?: V12;
}
/**
 * One line of the naturalist's log, written by the server from what happened.
 */
export interface Chronicle {
  text: Text1;
  tick: Tick5;
}
export interface ErrorMessage {
  payload: Error;
  type?: Type15;
  v?: V13;
}
export interface Error {
  code: Code;
  fatal: Fatal;
  message: Message;
}
export interface ReplayInfoMessage {
  payload: ReplayInfo;
  type?: Type16;
  v?: V14;
}
/**
 * Brackets a ghost: sent before its first frame (`done` false) and after its last.
 */
export interface ReplayInfo {
  born_tick: BornTick;
  causes: Causes1;
  died_tick: DiedTick;
  done: Done;
  lifespan: Lifespan1;
  lineage: Lineage4;
  name: Name4;
  owner: Owner5;
  speed: Speed1;
}
